### ISSUE TITLE
develop 폴더 트리 수정 건

### ISSUE THREAD

**Issue by BradleyyKim** [secondlinefirefist/caffeineMarket#9]
(slack에 프로젝트 채널 확인 부탁드립니다.) 

현재 develop 폴더 내 트리구조 및 파일 병합이 필요해 보입니다. 

1. reset.css 하나로 통합 완료 (주석으로 각 파트 정리 완료  ir, blind 차이 외에는 다른 점 없음) 
2. style.css -> 주제.css 로 이름 변경 완료 (ex. product.html 제작 시 css명 product.css 로 변경)
3. img 파일 경로 전체 변경 완료
4. static depth 제거
현재 이렇게 진행했습니다. 궁금하신 점 수정사항 언제든 피드백 부탁드립니다 :)

**Comment by greenT-Hee** [comment]
확인했습니다!

**Comment by jsk3342** [comment]
확인했습니다
